apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: px-prometheus
    prometheus: portworx
  name: px-prometheus
  namespace: kube-system
spec:
  endpoints:
  - path: /metrics
    port: web
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: px-prometheus
