apiVersion: v1
kind: Service
metadata:
  name: px-prometheus-service
  namespace: kube-system
  labels:
    app: px-prometheus-service
spec:
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    prometheus: px-prometheus
  type: ClusterIP
