{
 "title": "Portworx Volume Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "px_cluster_cpu_percent" } },
   {
    "name": "volumename",
    "label": "volumename",
    "query": {
     "query": "px_volume_depth_io {cluster=\"$cluster\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "All Volumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Avg Read Latency (1m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(px_volume_vol_read_latency_seconds{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Top n Volumes by Capacity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk (10,(px_volume_usage_bytes{cluster=~\"$cluster\"}/px_volume_capacity_bytes{cluster=~\"$cluster\"})*100)",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Top n Volumes by IO depth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,px_volume_depth_io{cluster=\"$cluster\"})",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Avg Write Latency (1m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(px_volume_vol_write_latency_seconds{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Replication Status",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "px_volume_replication_status{cluster=~\"$cluster\"}",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Volume: $volumename",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "Volumes",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Current Replication Level (HA)",
     "type": "gauge",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "px_volume_currhalevel{volumename=~\"$volumename\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{volumename}}",
       "measurement": "px_volume_halevel",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
        { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
       ]
      }
     ]
    },
    {
     "title": "I/O Priority",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "px_volume_iopriority{volumename=~\"$volumename\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{volumename}}",
       "measurement": "px_volume_halevel",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
        { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
       ]
      }
     ]
    },
    {
     "title": "Avg Read Latency",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(px_volume_dev_read_latency_seconds{cluster=~\"$cluster\",volumename=~\"$volumename\"})"
      }
     ]
    },
    {
     "title": "Avg Write Latency",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(px_volume_dev_write_latency_seconds{cluster=~\"$cluster\",volumename=~\"$volumename\"})"
      }
     ]
    },
    {
     "title": "Volume Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Disk Capacity",
       "expr": "px_volume_capacity_bytes{volumename=~\"$volumename\"}",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": " Capacity",
       "measurement": "px_volume_capacity_bytes",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
        { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
       ]
      },
      {
       "alias": "Disk Usage",
       "expr": "px_volume_usage_bytes{volumename=~\"$volumename\"}",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": " Usage",
       "measurement": "px_volume_usage_bytes",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
        { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
       ]
      }
     ]
    },
    {
     "title": "Configured Replication Level (HA)",
     "type": "gauge",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "px_volume_halevel{volumename=~\"$volumename\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{volumename}}",
       "measurement": "px_volume_halevel",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
        { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
       ]
      }
     ]
    },
    {
     "title": "Volume total reads/writes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Bytes Written Throughput",
       "expr": "px_volume_num_long_reads{volumename=~\"$volumename\"}",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "No. of  Reads ",
       "measurement": "px_volume_writethroughput",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
        { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
       ]
      },
      {
       "alias": "Bytes Read Throughput",
       "expr": "px_volume_num_long_writes{volumename=~\"$volumename\"}",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "No. of  Writes ",
       "measurement": "px_volume_readthroughput",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
        { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
       ]
      }
     ]
    },
    {
     "title": "Volume IOPs",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "Bytes Written Throughput",
       "expr": "px_volume_iops{volumename=~\"$volumename\"}",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "IOPs",
       "measurement": "px_volume_writethroughput",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
        { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
       ]
      }
     ]
    },
    {
     "title": "Volume Read/Written Bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Bytes Written Throughput",
       "expr": "px_volume_vol_read_bytes{volumename=~\"$volumename\"}",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Bytes Read ",
       "measurement": "px_volume_writethroughput",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
        { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
       ]
      },
      {
       "alias": "Bytes Read Throughput",
       "expr": "px_volume_vol_written_bytes{volumename=~\"$volumename\"}",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Bytes Written ",
       "measurement": "px_volume_readthroughput",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
        { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
       ]
      }
     ]
    },
    {
     "title": "Volume Latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "alias": "Read Latency",
       "expr": "px_volume_dev_read_latency_seconds{volumename=~\"$volumename\"}",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "legendFormat": "Read Latency",
       "measurement": "px_volume_vol_read_latency_seconds",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
        { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
       ]
      },
      {
       "alias": "Write Latency",
       "expr": "px_volume_dev_write_latency_seconds{volumename=~\"$volumename\"}\n",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "legendFormat": "Write Latency",
       "measurement": "px_volume_vol_write_latency_seconds",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
        { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
       ]
      }
     ]
    },
    {
     "title": "Volume IO Depth",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "px_volume_depth_io{volumename=~\"$volumename\"}",
       "legendFormat": "I/O Depth"
      }
     ]
    },
    {
     "title": "Volume Throughput",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "Bytes Written Throughput",
       "expr": "px_volume_readthroughput{volumename=~\"$volumename\"}",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Bytes Read Throughput",
       "measurement": "px_volume_writethroughput",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
        { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
       ]
      },
      {
       "alias": "Bytes Read Throughput",
       "expr": "px_volume_writethroughput{volumename=~\"$volumename\"}",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Bytes Written Throughput",
       "measurement": "px_volume_readthroughput",
       "select": [
        [
         { "params": [ "gauge" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "volumename", "operator": "=~", "value": "/^$Volumes$/" },
        { "condition": "AND", "key": "cluster", "operator": "=~", "value": "/^$Cluster$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Cloud Backup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Last Backup Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "px_backup_stats_status{volumename=~\"$volumename\"}"
    }
   ]
  },
  {
   "title": "Backup duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "px_backup_stats_duration_seconds{volumename=~\"$volumename\"}",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Backup Duration (Avg)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "px_backup_stats_duration_seconds{volumename=~\"$volumename\"}"
    }
   ]
  },
  {
   "title": "Backup Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "px_backup_stats_size{volumename=~\"$volumename\"}",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Backup Size (Avg)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "px_backup_stats_size{volumename=~\"$volumename\"}"
    }
   ]
  }
 ]
}